# Generated by Django 6.0.3 on 2026-03-21 19:25

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='about_heading',
            field=models.CharField(blank=True, default='About Bitesize Church', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_text',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='homepage',
            name='contact_heading',
            field=models.CharField(blank=True, default='Contact', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='contact_text',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='directions_text',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='events_heading',
            field=models.CharField(blank=True, default='Bitesize Brunch Dates', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='events_intro',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='facebook_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='feature_heading',
            field=models.CharField(blank=True, default='Bitesize Brunch', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='feature_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='feature_text',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='footer_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_button_link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_button_text',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_tagline',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='location_heading',
            field=models.CharField(blank=True, default='Location', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='location_text',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='map_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='parking_text',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.CreateModel(
            name='BrunchDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('event_date', models.DateField()),
                ('title', models.CharField(blank=True, default='Bitesize Brunch', max_length=255)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='brunch_dates', to='home.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
