# Generated by Django 6.0.3 on 2026-03-27
from django.db import migrations
import wagtail.fields

class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_homepage_about_heading_homepage_about_text_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="extra_sections",
            field=wagtail.fields.StreamField(
                [
                    ("heading", wagtail.blocks.CharBlock(form_classname="full title", icon="title")),
                    ("text", wagtail.blocks.RichTextBlock(icon="doc-full")),
                    ("image", wagtail.images.blocks.ImageChooserBlock(icon="image")),
                ],
                use_json_field=True,
                blank=True,
            ),
        ),
    ]
