# Generated by Django 6.0.3 on 2026-03-27 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepage_extra_sections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='parking_text',
            field=models.TextField(blank=True),
        ),
    ]
